### ISSUE TITLE
New CORS issue

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#432]
move the CORS stuff from the OAI endpoint to the root endpoint to allow JS to read pdf files from NABU. The current CORS is ok for the OAI feed, but js to read pdf needs it in NABU

**Comment by stasb** [comment]
This should now be fixed and deployed. Please let me know if further CORS issues arise.

**Comment by MLR-au** [comment]
hi guys,

I've just tried this out and I'm still having issues. The error I see in the browser is:

XMLHttpRequest cannot load http://catalog.paradisec.org.au/repository/AC2/VUNU105/AC2-VUNU105-texts.pdf. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://dev.local:9000' is therefore not allowed access.

As it turns out, I happened to be migrating to a new dev host today and part of the process involved setting up a new nginx server. Anyway, I saw the same issue. For reference, the relevant bits of config I have in my nginx config (a reverse proxy to the real Nabu) are:

      more_set_headers "Access-Control-Allow-Origin: $http_origin";
      add_header 'Access-Control-Allow-Credentials' 'true';

This is for the nginx server in the nginx-extras package on a Debian Wheezy server. Note that I explicitly set $http_origin. Other than that my config is exactly the same as that shown at http://enable-cors.org/server_nginx.html (if that helps).

Thanks.
