### ISSUE TITLE
unable to set bounding box on map

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#713]
when adding a new item , I try to move the bounding box o nthe map but it isn't working

**Comment by johnf** [comment]
fixed

**Comment by nthieberger** [comment]
still an issue with the map. I can't see it here: https://catalog.paradisec.org.au/collections/External/items/SikaianaCollection/edit
then the page becomes unresponsive (Chrome/mac)

**Comment by johnf** [comment]
@nthieberger Do you know where we got the original country boundaries from?

The data for Australia for example seems strange

![image](https://user-images.githubusercontent.com/42590/227646624-69ec1e95-14a2-4ad2-b7cc-3a2f86ba656d.png)

**Comment by johnf** [comment]
> still an issue with the map. I can't see it here: https://catalog.paradisec.org.au/collections/External/items/SikaianaCollection/edit
> then the page becomes unresponsive (Chrome/mac)
> Then it is editable and the map appears, but it is erratic in appearinfg sometimes and not others. Also, 'set map from language' isn't working (new ticket)

Is this easily reproducible for you?

Can you see if there is anything interesting happening in the browser console and paste it here

**Comment by nthieberger** [comment]
it is all working now
